#!/usr/bin/env bash
wget --content-disposition https://archlinux.org/packages/extra/x86_64/swww/download/
mkdir swww
mv swww-*.tar.zst swww/
cd swww
tar -xvf swww-*.tar.zst
sudo mv ./usr/bin/* /usr/local/bin/
cd ../
rm -rf swww
